### ISSUE TITLE
Multiple webview on a single scene/controller

### ISSUE THREAD

**Issue by joshuakaleb0424** [XWebView/XWebView#33] opened 2015-12-21 16:00 UTC
Whenever i try loading a plugin. Only the last webview to be loaded with a plugin works. The previous ones are not working.

**Comment by xwv** [comment] 2015-12-21 16:42
If you mean loading a plugin object into multiple webviews, yes, it's a known issue. I have not tried before, but I know it has problem.
So currently, you have to create 2 or more objects for each webview, And you have to deal with syncing if they need to share states.

**Comment by joshuakaleb0424** [comment] 2015-12-23 04:38
Like this?
self.firstWebView!.loadPlugin(FirstPlugin(), namespace: "plugin.object")
self.secondWebView!.loadPlugin(SecondPlugin(), namespace: "plugin.object")

**Comment by xwv** [comment] 2015-12-23 06:57
You can also load 2 objects instantiate from the same class for each webview, like:

self.firstWebView!.loadPlugin(FirstPlugin(), namespace: "plugin.object")
self.secondWebView!.loadPlugin(FirstPlugin(), namespace: "plugin.object")

**Comment by fernandodev** [comment] 2015-12-23 11:22
Does it make sense to share plugin between multiple webviews? 
I think that an injected object must have a single connection between view and model, but if I would like to listen some event? In this case it might be a better approach to create multiple instances of the same plugin and in callbacks send those events to a global listener...
What do you think about that @xwv ?

**Comment by xwv** [comment] 2015-12-23 17:46
@fernandodev, perhaps you are right.
Technically, the major problem of multiple webviews support is that how to know which webview is the origination of a native invocation. I can't figure out a decent way so far.

**Comment by xwv** [comment] 2016-03-30 19:15
This should be fixed with this [commit](https://github.com/XWebView/XWebView/commit/ad5751b742e481c43a35eda99c3d2d3161feda96) finally. This feature it's not well tested.

BTW, you should always use the same serial queue while loading a plugin into multiple webview, unless the plugin supports concurrency by design.

**Closed as completed by xwv** 2016-03-30 19:15 UTC
