### ISSUE TITLE
Build error with Swift 3.1

### ISSUE THREAD

**Issue by vanvalkenburg** [XWebView/XWebView#79] opened 2017-03-29 04:45 UTC
Building XWebView with Xcode 8.3 (which includes Swift 3.1) fails with compile error: [...]/Pods/XWebView/XWebView/XWVMetaObject.swift:88:32: Deinitializers cannot be accessed

**Comment by xwv** [comment] 2017-03-29 17:54
Can anybody confirm this issue? I can't install Xcode 8.3 because my macbook doesn't support 10.12.

**Comment by buscarini** [comment] 2017-03-30 07:57
confirmed. Happens here:

    let plugin: AnyClass
    fileprivate var members = [String: Member]()
    private static let exclusion: Set<Selector> = {
        var methods = instanceMethods(forProtocol: XWVScripting.self)
        methods.remove(#selector(XWVScripting.invokeDefaultMethod(withArguments😊))
        return methods.union([
            #selector(NSObject.deinit),
            #selector(NSObject.copy)
        ])
    }()

**Comment by buscarini** [comment] 2017-03-30 08:02
By the way, even after commenting that line it still doesn't compile, as it crashes the compiler:

    1.	While emitting IR SIL function @_TF8XWebView7jsonifyFGSQP__SS for 'jsonify' at /Users/josanchez/prog/forks/XWebView_treenovum/XWebView/XWVJson.swift:94:1

**Comment by SentoCrespo** [comment] 2017-03-30 08:04
+1 Please. Happens here as well.

**Comment by buscarini** [comment] 2017-03-30 08:06
I changed the exclamation point there to an interrogation point and then it compiled:

    func jsonify(_ value: Any!) -> String {

to

    func jsonify(_ value: Any?) -> String {

**Comment by xwv** [comment] 2017-03-30 17:45
@buscarini The jsonify issue was fixed in this [change](https://github.com/XWebView/XWebView/commit/454950082e228d49283245bb919f154d2678504c).

**Comment by vanvalkenburg** [comment] 2017-03-30 17:56
The build error disappears when commenting out the offending line `#selector(NSObject.deinit),`, though I cannot judge if that is an appropriate solution

**Comment by xwv** [comment] 2017-04-01 19:52
@vanvalkenburg , It should be OK to replace `#selector(NSObject.deinit)` with `Selector(("dealloc"))`.
It seems that the dealloc selector is no longer accessible in Swift 3.1.

**Comment by shadone** [comment] 2017-04-06 10:52
Hi. @xwv is there any update on this? I've created a pull request removing the use of `#selector(NSObject.deinit)` and it seems to be working fine with Swift 3.1 not breaking anything else:
https://github.com/XWebView/XWebView/issues/79

**Comment by xwv** [comment] 2017-04-07 13:35
Thanks for everybody's contribution.

BTW, I'm very happy to see more and more developers like and use the project. But I'm very busy on both working and personal affairs recent months. Please let me known if anyone is willing to maintain and contribute the project regularly, I would like to grant permissions to him/her.

**Comment by shadone** [comment] 2017-04-10 09:15
@xwv We are using XWebView internally in a beta project (and I am loving it thanks for working on it!). I wish I could say we will contribute back but at the moment I am the only iOS developer on the team and have limited amount of time. I wouldn't mind to help maintaining this project to the best of my abilities though, I will also raise this question internally.

In a mean time it would be amazing to release the fix so any potential users are not faced with the compile error. Since this are only two trivial (and backwards and forward compatible) fixes between 0.12.0 and master it should be safe to release it as a patch release 0.12.1. What do you think David?

**Comment by xwv** [comment] 2017-04-23 18:47
I have published 0.12.1 on cocoapods, sorry for the tardy release.

@shadone , do you have a [cocoapods account](https://guides.cocoapods.org/making/getting-setup-with-trunk.html)? I can add you as contributor, so you can publish new release when I absent.

**Closed as completed** 2017-04-23 18:47 UTC
